### ISSUE TITLE
Better readme

### ISSUE THREAD

**Issue by TomStary** [CCMi-FIT/UMLet-OntoUML-palette#1]
This file was quite helpful, but it lacks readme, at least a way how to use it would be nice. For another one who might step over this repo, the way you import this pallet into your standalone umlet:
- find where your standalone umlet folder is (where umlet.jar is located)
- you'll find that there is folder pallets
- just paste `.uxf` file from this repo there
- restart any running Umlet app you might have

**Comment by roper79** [comment]
Thanks a lot, @TomStary, I updated the readme.
